<a href="https://colab.research.google.com/github/Shifahu/TTA/blob/main/HLTWK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
array = np.array(["true", "true", "true","true", "true", "true","true", "true", "true"])
new_array = array.reshape(3,3)

print(new_array)

[['true' 'true' 'true']
 ['true' 'true' 'true']
 ['true' 'true' 'true']]


In [2]:
import numpy as np

arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [3]:
import numpy as np 
 
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
odd_values = (a%2 == 1) 
a[odd_values] = -1 
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [3]:
import numpy as np
arr = (np.arange(8)).reshape(2,4)

print(arr)

[[0 1 2 3]
 [4 5 6 7]]


In [30]:
import numpy as np

a = np.arange(1,9).reshape(2,4)
b = np.arange(9,17).reshape(2,4)
c = np.dot(a,b)
#print(c)


e = np.sum(c,axis = 0)
print(e)


ValueError: ignored

The answer above, I want to figure out why it's not working

In [29]:
import numpy as np

a = np.arange(1,10).reshape(3,3)
b= np.arange(10,19).reshape(3,3)
c = np.dot(a,b)

print(c)

e = np.sum(c,axis = 1)
print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]


In [2]:
from google.colab import drive
drive.mount('/content/drive')




Mounted at /content/drive


In [3]:
import pandas as pd

path = "/content/drive/MyDrive/Countries.csv.numbers"
df = pd.read_csv(path)

ParserError: ignored